version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres/${DB_DATABASE}
      ANOTHER_ENV_VAR: value_for_env_var
    env_file:
      - .env
    ports:
      - "5001:5001"

  frontend:
    build: ./us-inventory-react-app
    volumes:
      - ./us-inventory-react-app:/app
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  pgdata:
